version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: circlematch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://app:password@db:5432/circlematch
      GOOGLE_CLIENT_ID: "1094992986255-n19onlta1qmm7h2q34r4u1iugiqkrk0c.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: "1094992986255-n19onlta1qmm7h2q34r4u1iugiqkrk0c.apps.googleusercontent.com"
    depends_on:
      - backend

volumes:
  postgres_data: